# Generated by Django 2.2.6 on 2020-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IMEIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=225)),
                ('King', models.BooleanField(default=False)),
                ('Queen', models.BooleanField(default=False)),
                ('Mister', models.BooleanField(default=False)),
                ('Miss', models.BooleanField(default=False)),
                ('popu', models.BooleanField(default=False)),
                ('cos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('king', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KingQueenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=225)),
                ('major', models.CharField(default='BE', max_length=225)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='KingQueenData')),
            ],
        ),
        migrations.CreateModel(
            name='Miss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mister', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MisterMissData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=225)),
                ('major', models.CharField(default='BE', max_length=225)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='MisterMissData')),
            ],
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queen', models.IntegerField()),
            ],
        ),
    ]
