# Generated by Django 2.2.6 on 2020-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20200225_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popmiss',
            name='pmiss',
            field=models.IntegerField(),
        ),
    ]
