# Generated by Django 2.2.6 on 2020-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_auto_20200225_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopKing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PopQueen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqueen', models.IntegerField()),
            ],
        ),
    ]
