# Generated by Django 2.2.6 on 2020-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_popking_popqueen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imeis',
            name='popKing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imeis',
            name='popQueen',
            field=models.BooleanField(default=False),
        ),
    ]
