# Generated by Django 2.2.6 on 2020-02-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_auto_20200226_0648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopKing',
        ),
        migrations.DeleteModel(
            name='PopQueen',
        ),
        migrations.RemoveField(
            model_name='imeis',
            name='popKing',
        ),
        migrations.RemoveField(
            model_name='imeis',
            name='popQueen',
        ),
    ]
