# Generated by Django 2.2.6 on 2020-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_auto_20200226_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.FileField(upload_to='App')),
            ],
        ),
    ]
